/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class name_antonsmirnov_android_acra_breakpad_NativeExceptionHandler */

#ifndef _Included_name_antonsmirnov_android_acra_breakpad_NativeExceptionHandler
#define _Included_name_antonsmirnov_android_acra_breakpad_NativeExceptionHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     name_antonsmirnov_android_acra_breakpad_NativeExceptionHandler
 * Method:    nativeSetReportsDirectory
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_name_antonsmirnov_android_acra_1breakpad_NativeExceptionHandler_nativeSetReportsDirectory
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
