/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class name_antonsmirnov_android_acra_breakpad_app_NativeLib */

#ifndef _Included_name_antonsmirnov_android_acra_breakpad_app_NativeLib
#define _Included_name_antonsmirnov_android_acra_breakpad_app_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     name_antonsmirnov_android_acra_breakpad_app_NativeLib
 * Method:    native_func
 * Signature: (Ljava/lang/String;Ljava/util/List;Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_name_antonsmirnov_android_acra_1breakpad_app_NativeLib_native_1func
  (JNIEnv *, jclass, jstring, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
